import os

replacements = [
    ('lang="es"', 'lang="en"'),
    ('Informe Diario de Mercado', 'Daily Market Intelligence Report'),
    ('Informe Mercado Crypto', 'Crypto Market Intelligence Report'),
    ('Informe Mercado Divisas', 'Forex Market Intelligence Report'),
    ('Informe Diario - Market Scan & Value', 'Daily Report - Market Scan & Value'),
    ('Informe Diario - Crypto Intelligence', 'Daily Report - Crypto Intelligence'),
    ('Informe Diario - Mercado Divisas', 'Daily Report - Forex Market'),
    ('Contexto Macroeconomico & Sentimiento', 'Macroeconomic Context & Market Sentiment'),
    ('Contexto Macro & Sentimiento', 'Macroeconomic Context & Market Sentiment'),
    ('Contexto Macro &amp; Sentiment', 'Macro Context & Market Sentiment'),
    ('Contexto Macro &amp; Se', 'Macro Context & Market Sentiment'),
    ('Volatilidad', 'Volatility'),
    ('respecto ayer', 'vs yesterday'),
    ('Bonos 10Y (TNX)', '10Y Treasury Yield (TNX)'),
    ('Dolar', 'US Dollar'),
    ('Dólar', 'US Dollar'),
    ('Fuerza USD', 'USD Strength'),
    ('Eventos Clave del Calendario Económico Hoy', 'Key Economic Calendar Events Today'),
    ('IMPACTO', 'IMPACT'),
    ('ALTO IMPACTO', 'HIGH IMPACT'),
    ('MEDIO IMPACTO', 'MEDIUM IMPACT'),
    ('Senales LONG — Compra / Alcista', 'LONG Signals — Buy / Bullish Setups'),
    ('Señales LONG — Compra / Alcista', 'LONG Signals — Buy / Bullish Setups'),
    ('Senales LONG &mdash; Compra / Alcista', 'LONG Signals &mdash; Buy / Bullish Setups'),
    ('Señales LONG &mdash; Compra / Alcista', 'LONG Signals &mdash; Buy / Bullish Setups'),
    ('Senales SHORT — Venta / Bajista', 'SHORT Signals — Sell / Bearish Setups'),
    ('Señales SHORT — Venta / Bajista', 'SHORT Signals — Sell / Bearish Setups'),
    ('Senales SHORT &mdash; Venta / Bajista', 'SHORT Signals &mdash; Sell / Bearish Setups'),
    ('Señales SHORT &mdash; Venta / Bajista', 'SHORT Signals &mdash; Sell / Bearish Setups'),
    ('Gestión de Riesgo', 'Risk & Capital Management'),
    ('Gestion de Riesgo', 'Risk & Capital Management'),
    ('Auditoria', 'Audit & Tracking'),
    ('Auditoría', 'Audit & Tracking'),
    ('Volver al Hub', 'Back to Hub'),
    ('Ver Analytics & Win Rate', 'View Analytics & Win Rate'),
    ('>Entrada<', '>Entry<'),
    ('>Entrada</span>', '>Entry</span>'),
    ('MODERADO', 'MODERATE'),
    ('BAJO', 'LOW'),
    ('de Julio de', 'July'),
    ('de Julio,', 'July'),
    ('22 de July de 2026', 'July 22, 2026'),
    ('21 de July de 2026', 'July 21, 2026'),
    ('20 de July de 2026', 'July 20, 2026'),
    ('17 de July de 2026', 'July 17, 2026'),
    ('16 de July de 2026', 'July 16, 2026'),
    ('de Febrero de', 'February'),
    ('de Febrero,', 'February'),
    ('No se encontraron oportunidades LONG hoy.', 'No LONG opportunities identified today.'),
    ('No se encontraron oportunidades SHORT hoy.', 'No SHORT opportunities identified today.'),
    ('Activos con configuracion tecnica alcista: sobreventa, ruptura al alza o tendencia confirmada.', 'Assets displaying bullish technical setups: oversold bounce, breakout or trend continuation.'),
    ('Activos en zona de sobrecompra extrema o ruptura bajista bajo SMA50.', 'Assets in extreme overbought territory or breaking down below key moving averages.'),
    ('Pares en sobreventa o con momentum alcista confirmado.', 'Pairs in oversold territory or with confirmed bullish momentum.'),
    ('Pares en sobrecompra extrema con potencial de reversion a la media.', 'Pairs in overbought territory with potential for mean reversion.'),
    ('Criptos con sobreventa, momentum alcista o acumulacion sobre SMA50.', 'Cryptos displaying RSI oversold bounce, volume breakout or SMA50 support.'),
    ('Criptos en sobrecompra extrema o ruptura bajista bajo SMA50.', 'Cryptos in extreme overbought territory or breakdown below SMA50.'),
    ('Senales generadas algoritmicamente y auditadas en tiempo real.', 'Signals generated algorithmically and tracked in real-time.'),
    ('Señales generadas algorítmicamente y auditadas en tiempo real.', 'Signals generated algorithmically and tracked in real-time.'),
    ('Total Senales Hoy', 'Total Signals Today'),
    ('Total Señales Hoy', 'Total Signals Today'),
    ('julio', 'July'),
    ('febrero', 'February'),
    ('Monitor de Señales', 'Signals Monitor'),
    ('Señales Totales', 'Total Signals'),
    ('Error cargando las señales. Verifique el formato de los datos.', 'Error loading signals. Please check data format.'),
    ('señales...', 'signals...'),
    ('No se han podido verificar datos concluyentes para el informe de hoy', 'Could not verify conclusive market data for today\'s report'),
    ('Generado por Antigravity Autonomous System', 'Generated by Antigravity Autonomous System'),
    ('Mantener riesgo por operación en 1-2% del capital total.', 'Maintain risk per trade at 1-2% of total account capital.'),
    ('Evita operar durante NFP, FOMC o IPC si no gestionas bien la volatilidad.', 'Avoid trading during NFP, FOMC, or CPI news events if high volatility is unmanaged.'),
    ('El mercado 24/7 no perdona.', 'The 24/7 market requires strict Stop Loss orders.'),
    ('El mercado de divisas cierra los viernes. Evita dejar posiciones abiertas durante el fin de semana para prevenir gaps.', 'Forex markets close on Fridays. Avoid holding open positions over the weekend to prevent gap slippage.'),
    ('Generado por Antigravity Autonomous System', 'Generated by Antigravity Autonomous System'),
    ('Generado por Antigravity Crypto System', 'Generated by Antigravity Autonomous Crypto System'),
    ('Generado por Antigravity Forex System', 'Generated by Antigravity Autonomous Forex System')
]

count = 0
for root, dirs, files in os.walk('.'):
    if '.git' in root or '.venv' in root:
        continue
    for file in files:
        if file.endswith('.html'):
            path = os.path.join(root, file)
            with open(path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            modified = False
            for k, v in replacements:
                if k in content:
                    content = content.replace(k, v)
                    modified = True
            
            if modified:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f'Translated: {path}')
                count += 1

print(f'Total HTML files cleaned: {count}')
